package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/cameron/yggdrasil/pkg/git"
	"github.com/spf13/cobra"
)

var initForce bool

func initCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "init",
		Short: "Create a .yggdrasil.toml with auto-detected defaults",
		Long:  `Scans the repo for config files, env files, certs, and ecosystem markers, then generates a commented .yggdrasil.toml tailored to your project.`,
		Args:  cobra.NoArgs,
		RunE:  runInit,
	}
	cmd.Flags().BoolVar(&initForce, "force", false, "overwrite an existing .yggdrasil.toml")
	return cmd
}

func runInit(cmd *cobra.Command, args []string) error {
	repoDir, err := os.Getwd()
	if err != nil {
		return fmt.Errorf("getting current directory: %w", err)
	}

	configPath := filepath.Join(repoDir, ".yggdrasil.toml")
	if _, err := os.Stat(configPath); err == nil && !initForce {
		return fmt.Errorf(".yggdrasil.toml already exists — use --force to overwrite")
	}

	content := generateConfig(repoDir)

	if err := os.WriteFile(configPath, []byte(content), 0644); err != nil {
		return fmt.Errorf("writing .yggdrasil.toml: %w", err)
	}

	fmt.Println("Created .yggdrasil.toml — review and adjust as needed.")
	return nil
}

func generateConfig(repoDir string) string {
	var b strings.Builder

	trunk := detectTrunk(repoDir)
	copyPatterns := detectCopyPatterns(repoDir)
	linkPatterns := detectLinkPatterns(repoDir)
	ecosystem := detectEcosystem(repoDir)
	postCreate := suggestPostCreate(ecosystem)

	// Header
	b.WriteString("# Yggdrasil configuration — generated by `yg init`\n")
	b.WriteString("# Edit this file to customize provisioning and hooks for your project.\n")
	b.WriteString("# Docs: https://github.com/cameron/yggdrasil\n")
	b.WriteString("\n")

	// [general]
	b.WriteString("[general]\n")
	b.WriteString(fmt.Sprintf("trunk = %q\n", trunk))
	b.WriteString("# Auto-detected. Omit to let yg detect at runtime.\n")
	b.WriteString("# path_template = \"../{repo}.{branch}\"\n")
	b.WriteString("# Default template: worktrees are siblings of the primary checkout.\n")
	b.WriteString("# {repo} expands to the repo directory name, {branch} to the branch name.\n")
	b.WriteString("# Branch names with slashes (e.g. chore/foo) are dash-sanitized (chore-foo).\n")
	b.WriteString("# merge_strategy = \"squash\"  # squash | merge | ff\n")
	b.WriteString("# sync_strategy = \"rebase\"   # rebase | merge\n")
	b.WriteString("\n")

	// [provision]
	b.WriteString("[provision]\n")
	b.WriteString("# Files to COPY from the primary worktree into each new tree.\n")
	b.WriteString("# Copied files are independent — edits in one tree don't affect others.\n")
	b.WriteString("# Patterns are gitignore-style; absolute paths and .. are rejected.\n")
	if len(copyPatterns) > 0 {
		b.WriteString(fmt.Sprintf("copy = %s\n", formatTomlList(copyPatterns)))
	} else {
		b.WriteString("copy = []  # e.g. [\".env\", \".env.*\", \"appsettings.Development.json\"]\n")
	}
	b.WriteString("\n")
	b.WriteString("# Files to LINK (symlink) from the primary into each new tree.\n")
	b.WriteString("# Linked files stay in sync — edits propagate to all trees.\n")
	b.WriteString("# Use for shared certs, editor config, or anything that should track the primary.\n")
	if len(linkPatterns) > 0 {
		b.WriteString(fmt.Sprintf("link = %s\n", formatTomlList(linkPatterns)))
	} else {
		b.WriteString("link = []  # e.g. [\"certs/dev.pem\", \".vscode/settings.json\"]\n")
	}
	b.WriteString("\n")

	// [hooks]
	b.WriteString("[hooks]\n")
	b.WriteString("# Lifecycle hooks — each is an ordered list of shell commands run via sh -c.\n")
	b.WriteString("# pre_create runs in the primary worktree; post_create runs in the new tree.\n")
	b.WriteString("# pre_remove / post_remove run in the primary.\n")
	b.WriteString("# Every hook receives: YG_WORKTREE, YG_PRIMARY, YG_BRANCH, YG_TRUNK,\n")
	b.WriteString("#   YG_REPO, YG_PROFILE, YG_EVENT, YG_AGENT_OWNED\n")
	b.WriteString("pre_create = []\n")
	if len(postCreate) > 0 {
		b.WriteString(fmt.Sprintf("post_create = %s\n", formatTomlList(postCreate)))
	} else {
		b.WriteString("post_create = []  # e.g. [\"pnpm install\"] or [\"go mod download\"]\n")
	}
	b.WriteString("pre_remove = []\n")
	b.WriteString("post_remove = []\n")
	b.WriteString("# pre_merge = [\"pnpm test\", \"pnpm lint\"]\n")
	b.WriteString("# post_merge = []\n")

	return b.String()
}

// detectTrunk returns the trunk branch name, falling back to "main".
func detectTrunk(repoDir string) string {
	g := git.New(repoDir)
	trunk, err := g.DetectTrunk()
	if err != nil || trunk == "" {
		return "main"
	}
	return trunk
}

// detectCopyPatterns scans for env files and local config files that should be
// copied into each worktree.
func detectCopyPatterns(repoDir string) []string {
	var patterns []string
	seen := make(map[string]bool)

	// Env files
	envCandidates := []string{
		".env",
		".env.local",
		".env.development",
		".env.production",
		".env.staging",
	}
	for _, name := range envCandidates {
		if fileExists(repoDir, name) && !seen[name] {
			patterns = append(patterns, name)
			seen[name] = true
		}
	}

	// If .env exists, also add the glob pattern for variants
	if seen[".env"] {
		// Already have .env; add .env.* if any variants exist
		if seen[".env.local"] || seen[".env.development"] || seen[".env.production"] || seen[".env.staging"] {
			// Use the glob instead of listing each one
			// Replace individual entries with the glob
			patterns = []string{".env", ".env.*"}
			seen[".env.local"] = true // mark as handled
		}
	}

	// .NET appsettings
	appsettingsCandidates := []string{
		"appsettings.Development.json",
		"appsettings.Local.json",
		"appsettings.Staging.json",
	}
	for _, name := range appsettingsCandidates {
		if fileExists(repoDir, name) && !seen[name] {
			patterns = append(patterns, name)
			seen[name] = true
		}
	}

	// Rails/django secrets
	secretCandidates := []string{
		"config/database.yml",
		"config/secrets.yml",
	}
	for _, name := range secretCandidates {
		if fileExists(repoDir, name) && !seen[name] {
			patterns = append(patterns, name)
			seen[name] = true
		}
	}

	return patterns
}

// detectLinkPatterns scans for cert files and shared config that should be
// symlinked rather than copied.
func detectLinkPatterns(repoDir string) []string {
	var patterns []string

	// Certificate files
	certDirs := []string{"certs", "cert", "ssl", "tls"}
	for _, dir := range certDirs {
		dirPath := filepath.Join(repoDir, dir)
		entries, err := os.ReadDir(dirPath)
		if err != nil {
			continue
		}
		for _, entry := range entries {
			if entry.IsDir() {
				continue
			}
			ext := strings.ToLower(filepath.Ext(entry.Name()))
			if ext == ".pem" || ext == ".crt" || ext == ".key" || ext == ".p12" || ext == ".pfx" {
				patterns = append(patterns, filepath.Join(dir, entry.Name()))
			}
		}
	}

	return patterns
}

// ecosystem represents the detected project type.
type ecosystem string

const (
	ecosystemNone     ecosystem = ""
	ecosystemNode     ecosystem = "node"
	ecosystemPython   ecosystem = "python"
	ecosystemGo       ecosystem = "go"
	ecosystemRust     ecosystem = "rust"
	ecosystemDotnet   ecosystem = "dotnet"
)

// detectEcosystem inspects the repo for project files and returns the
// detected ecosystem.
func detectEcosystem(repoDir string) ecosystem {
	// Node: package.json + lockfile determines package manager
	if fileExists(repoDir, "package.json") {
		return ecosystemNode
	}
	// Python: pyproject.toml, setup.py, requirements.txt, Pipfile
	if fileExists(repoDir, "pyproject.toml") || fileExists(repoDir, "setup.py") ||
		fileExists(repoDir, "requirements.txt") || fileExists(repoDir, "Pipfile") {
		return ecosystemPython
	}
	// Go: go.mod
	if fileExists(repoDir, "go.mod") {
		return ecosystemGo
	}
	// Rust: Cargo.toml
	if fileExists(repoDir, "Cargo.toml") {
		return ecosystemRust
	}
	// .NET: *.csproj, *.fsproj, *.sln
	matches, _ := filepath.Glob(filepath.Join(repoDir, "*.csproj"))
	if len(matches) > 0 {
		return ecosystemDotnet
	}
	matches, _ = filepath.Glob(filepath.Join(repoDir, "*.sln"))
	if len(matches) > 0 {
		return ecosystemDotnet
	}
	matches, _ = filepath.Glob(filepath.Join(repoDir, "*.fsproj"))
	if len(matches) > 0 {
		return ecosystemDotnet
	}
	return ecosystemNone
}

// suggestPostCreate returns hook commands appropriate for the ecosystem.
func suggestPostCreate(ec ecosystem) []string {
	switch ec {
	case ecosystemNode:
		// Detect which package manager
		repoDir, _ := os.Getwd()
		if fileExists(repoDir, "pnpm-lock.yaml") {
			return []string{"pnpm install"}
		}
		if fileExists(repoDir, "yarn.lock") {
			return []string{"yarn install"}
		}
		if fileExists(repoDir, "bun.lockb") || fileExists(repoDir, "bun.lock") {
			return []string{"bun install"}
		}
		return []string{"npm install"}
	case ecosystemPython:
		return []string{"python -m venv .venv", ".venv/bin/pip install -e ."}
	case ecosystemGo:
		return []string{"go mod download"}
	case ecosystemRust:
		return []string{"cargo build"}
	case ecosystemDotnet:
		return []string{"dotnet restore", "dotnet build"}
	default:
		return nil
	}
}

func fileExists(dir, name string) bool {
	_, err := os.Stat(filepath.Join(dir, name))
	return err == nil
}

func formatTomlList(items []string) string {
	if len(items) == 0 {
		return "[]"
	}
	quoted := make([]string, len(items))
	for i, item := range items {
		quoted[i] = fmt.Sprintf("%q", item)
	}
	return "[" + strings.Join(quoted, ", ") + "]"
}
